apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-manager-role
rules:
  - apiGroups: ["mysql.asrk.dev"]
    resources: ["mysqls", "mysqlbackups", "mysqlrestores", "mysqlclones"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["mysql.asrk.dev"]
    resources: ["mysqls/status", "mysqlbackups/status", "mysqlrestores/status", "mysqlclones/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["mysql.asrk.dev"]
    resources: ["mysqls/finalizers", "mysqlbackups/finalizers", "mysqlrestores/finalizers", "mysqlclones/finalizers"]
    verbs: ["update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
