apiVersion: v1
kind: Secret
metadata:
  name: my-mysql-root
  namespace: default
type: Opaque
stringData:
  password: "change-me-please"
---
apiVersion: mysql.asrk.dev/v1alpha1
kind: MySQL
metadata:
  name: secured-mysql
  namespace: default
spec:
  image: mysql:8.0
  storageSize: 5Gi
  database: app
  rootPasswordSecretRef:
    name: my-mysql-root
    key: password
