//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *FailoverSpec) DeepCopyInto(out *FailoverSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.UnhealthySeconds != nil {
		in, out := &in.UnhealthySeconds, &out.UnhealthySeconds
		*out = new(int32)
		**out = **in
	}
}

func (in *FailoverSpec) DeepCopy() *FailoverSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQL) DeepCopyInto(out *MySQL) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MySQL) DeepCopy() *MySQL {
	if in == nil {
		return nil
	}
	out := new(MySQL)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQL) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MySQLList) DeepCopyInto(out *MySQLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MySQL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MySQLList) DeepCopy() *MySQLList {
	if in == nil {
		return nil
	}
	out := new(MySQLList)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MySQLSpec) DeepCopyInto(out *MySQLSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.RootPasswordSecretRef != nil {
		in, out := &in.RootPasswordSecretRef, &out.RootPasswordSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.ReplicationPasswordSecretRef != nil {
		in, out := &in.ReplicationPasswordSecretRef, &out.ReplicationPasswordSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Failover != nil {
		in, out := &in.Failover, &out.Failover
		*out = new(FailoverSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *MySQLSpec) DeepCopy() *MySQLSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQLStatus) DeepCopyInto(out *MySQLStatus) {
	*out = *in
	if in.PrimaryUnhealthySince != nil {
		in, out := &in.PrimaryUnhealthySince, &out.PrimaryUnhealthySince
		*out = (*in).DeepCopy()
	}
	if in.LastFailoverTime != nil {
		in, out := &in.LastFailoverTime, &out.LastFailoverTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MySQLStatus) DeepCopy() *MySQLStatus {
	if in == nil {
		return nil
	}
	out := new(MySQLStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupS3Spec) DeepCopyInto(out *BackupS3Spec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

func (in *BackupS3Spec) DeepCopy() *BackupS3Spec {
	if in == nil {
		return nil
	}
	out := new(BackupS3Spec)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQLBackup) DeepCopyInto(out *MySQLBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MySQLBackup) DeepCopy() *MySQLBackup {
	if in == nil {
		return nil
	}
	out := new(MySQLBackup)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQLBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MySQLBackupList) DeepCopyInto(out *MySQLBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MySQLBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MySQLBackupList) DeepCopy() *MySQLBackupList {
	if in == nil {
		return nil
	}
	out := new(MySQLBackupList)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQLBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MySQLBackupSpec) DeepCopyInto(out *MySQLBackupSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(BackupS3Spec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *MySQLBackupSpec) DeepCopy() *MySQLBackupSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLBackupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MySQLBackupStatus) DeepCopyInto(out *MySQLBackupStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MySQLBackupStatus) DeepCopy() *MySQLBackupStatus {
	if in == nil {
		return nil
	}
	out := new(MySQLBackupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretNameRef) DeepCopyInto(out *SecretNameRef) {
	*out = *in
}

func (in *SecretNameRef) DeepCopy() *SecretNameRef {
	if in == nil {
		return nil
	}
	out := new(SecretNameRef)
	in.DeepCopyInto(out)
	return out
}

